name: Organize

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  organize:
    runs-on: ubuntu-latest
    continue-on-error: true # Because step 3 will errors out if there is no new commits

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: self

      - name: Checkout Lucaslhm/Flipper-IRDB
        uses: actions/checkout@v4
        with:
          path: Flipper-IRDB
          repository: Lucaslhm/Flipper-IRDB

      - name: Check if the repo updated
        run: |
          set +e
          cd Flipper-IRDB
          git log -1 --pretty=%H > ../irdb_commit.sha
          cmp -s ../irdb_commit.sha ../self/.github/workflows/irdb_commit.sha
          echo "NEW_COMMIT_PUSHED=$?" >> $GITHUB_ENV

      - name: Exits if repo is not updated
        if: (( ${{ env.NEW_COMMIT_PUSHED }} != 1 ))
        run: |
          echo $NEW_COMMIT_PUSHED
          exit 1

      - name: Setup Python
        uses: actions/setup-python@v5.1.0

      - name: Run script
        run: python3 self/.github/workflows/main.py ./Flipper-IRDB ./self

      - name: Push changes
        uses: actions4git/add-commit-push@v1
        with:
          path: ./self
          commit-message: "Auto-update ${{ steps.date.outputs.date }}"

      - name: Add the artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./self
